url: ['http://itea.ua/courses-itea/python/python-advanced/',
#        'https://www.fullstackpython.com/best-python-resources.html',
#        'https://pymotw.com/3/',
#        'https://www.python.org/dev/peps/pep-0020/',
        ]

requests: ['Python', 'Абстрактная фабрика', 'Контакты', 'Программы на языке Python',
          'быстрая белка', 'list comprehension', 'hashlib', 'asyncio', 'Coroutines']

page_limit: 8